import { useMemo, useState } from 'react'
import { CheckCircle2, Save } from 'lucide-react'
import { useFetch } from '../../hooks/useFetch'
import { teacherService } from '../../services/teacher.service'
import { attendanceService } from '../../services/attendance.service'
import { gradeService } from '../../services/grade.service'
import { bonusService } from '../../services/bonus.service'
import Loader from '../ui/Loader'
import EmptyState from '../ui/EmptyState'
import Button from '../ui/Button'

const today=()=>new Date().toISOString().slice(0,10)
export default function TeacherActionWorkspace({teacher,mode}){
 const students=useFetch(()=>teacherService.getMyStudents(),[]); const [groupId,setGroupId]=useState(''),[date,setDate]=useState(today()),[selected,setSelected]=useState(''),[value,setValue]=useState(''),[reason,setReason]=useState(''),[statuses,setStatuses]=useState({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const groups=useMemo(()=>{const m=new Map();(students.data||[]).forEach(s=>s.groupId&&m.set(s.groupId,s.groupName||'Sinf'));return [...m].map(([id,name])=>({id,name}))},[students.data]); const active=groupId||groups[0]?.id||''; const list=(students.data||[]).filter(s=>s.groupId===active)
 if(students.isLoading)return <Loader/>; if(!students.data?.length)return <EmptyState message="Sizga biriktirilgan sinflarda o‘quvchi topilmadi."/>
 async function saveAttendance(){setBusy(true);setMessage('');try{for(const s of list){await attendanceService.create({studentId:s.id,groupId:active,subjectId:teacher.subjectId,date,status:statuses[s.id]||'PRESENT'})}setMessage('Davomat saqlandi.');setStatuses({})}catch(e){setMessage(e?.response?.data?.message||'Davomatni saqlab bo‘lmadi.')}finally{setBusy(false)}}
 async function saveOne(){if(!selected||!value)return;setBusy(true);setMessage('');try{if(mode==='grade')await gradeService.create({studentId:selected,subjectId:teacher.subjectId,value:Number(value),date});else await bonusService.create({studentId:selected,points:Number(value),reason,date});setMessage(mode==='grade'?'Baho saqlandi.':'Bonus saqlandi.');setSelected('');setValue('');setReason('')}catch(e){setMessage(e?.response?.data?.message||'Saqlab bo‘lmadi.')}finally{setBusy(false)}}
 return <div className="space-y-4"><div className="grid gap-3 rounded-3xl border border-slate-200 bg-white p-4 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Sinf<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3" value={active} onChange={e=>{setGroupId(e.target.value);setSelected('')}}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Sana<input type="date" className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3" value={date} onChange={e=>setDate(e.target.value)}/></label></div>
 {mode==='attendance'?<div className="space-y-2">{list.map(s=><div key={s.id} className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:flex-row sm:items-center sm:justify-between"><div><b>{s.firstName} {s.lastName}</b><p className="text-xs text-slate-500">{s.groupName}</p></div><div className="grid grid-cols-2 gap-2 sm:flex">{[['PRESENT','Keldi'],['ABSENT','Kelmadi'],['LATE','Kechikdi'],['EXCUSED','Sababli']].map(([k,l])=><button type="button" key={k} onClick={()=>setStatuses(x=>({...x,[s.id]:k}))} className={`rounded-xl px-3 py-2 text-xs font-semibold ${(statuses[s.id]||'PRESENT')===k?'bg-slate-900 text-white':'bg-slate-100 text-slate-600'}`}>{l}</button>)}</div></div>)}<Button onClick={saveAttendance} isLoading={busy} className="w-full sm:w-auto"><Save size={16}/>Davomatni saqlash</Button></div>:<div className="rounded-3xl border border-slate-200 bg-white p-5"><label className="text-sm font-medium">O‘quvchi<select className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Tanlang</option>{list.map(s=><option key={s.id} value={s.id}>{s.firstName} {s.lastName}</option>)}</select></label><label className="mt-4 block text-sm font-medium">{mode==='grade'?'Baho (1–5)':'Bonus ball'}<input type="number" min="1" max={mode==='grade'?5:1000} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3" value={value} onChange={e=>setValue(e.target.value)}/></label>{mode==='bonus'&&<label className="mt-4 block text-sm font-medium">Sabab<textarea rows={3} className="mt-2 w-full rounded-xl border border-slate-200 p-3" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Masalan: darsdagi faolligi uchun"/></label>}<Button onClick={saveOne} isLoading={busy} className="mt-4 w-full"><Save size={16}/>Saqlash</Button></div>}
 {message&&<div className="flex items-center gap-2 rounded-2xl bg-teal-50 p-3 text-sm text-teal-800"><CheckCircle2 size={17}/>{message}</div>}</div>
}
