import { useState } from 'react'
import { Plus, UsersRound } from 'lucide-react'
import { useFetch } from '../../hooks/useFetch'
import { parentService } from '../../services/parent.service'
import { studentService } from '../../services/student.service'
import PageHeader from '../../components/ui/PageHeader'
import Button from '../../components/ui/Button'
import Modal from '../../components/ui/Modal'
import FormField, { inputClass } from '../../components/ui/FormField'
import Loader from '../../components/ui/Loader'
import ErrorState from '../../components/ui/ErrorState'
const EMPTY={firstName:'',lastName:'',email:'',password:'',phone:'',studentId:''}
export default function Parents(){const parents=useFetch(()=>parentService.getAll(),[]), students=useFetch(()=>studentService.getAll(),[]);const[open,setOpen]=useState(false),[form,setForm]=useState(EMPTY),[busy,setBusy]=useState(false),[err,setErr]=useState('');async function submit(e){e.preventDefault();setBusy(true);setErr('');try{await parentService.createWithAccount(form);setForm(EMPTY);setOpen(false);parents.refetch()}catch(e){const m=e?.response?.data?.message||'Ota-ona qo‘shilmadi.';setErr(Array.isArray(m)?m[0]:m)}finally{setBusy(false)}}return <div><PageHeader title="Ota-onalar" description="Ota-ona hisobini yarating va farzandiga bog‘lang." action={<Button onClick={()=>setOpen(true)}><Plus size={16}/>Ota-ona qo‘shish</Button>}/>{(parents.isLoading||students.isLoading)&&<Loader/>}{(parents.error||students.error)&&<ErrorState/>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{(parents.data||[]).map(p=><div key={p.id} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-amber-50 text-amber-700"><UsersRound size={19}/></div><div><b>{p.firstName} {p.lastName}</b><p className="text-xs text-slate-500">{p.email}</p></div></div><p className="mt-4 text-sm text-slate-600">Farzandi: <b className="text-slate-900">{p.childFirstName} {p.childLastName}</b></p></div>)}</div><Modal title="Yangi ota-ona" isOpen={open} onClose={()=>setOpen(false)}><form onSubmit={submit}><div className="grid gap-3 sm:grid-cols-2"><FormField label="Ism"><input required className={inputClass} value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></FormField><FormField label="Familiya"><input required className={inputClass} value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></FormField></div><FormField label="Email"><input required type="email" className={inputClass} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></FormField><FormField label="Boshlang‘ich parol"><input required minLength={8} className={inputClass} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></FormField><FormField label="Telefon"><input className={inputClass} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></FormField><FormField label="Farzand"><select required className={inputClass} value={form.studentId} onChange={e=>setForm({...form,studentId:e.target.value})}><option value="">O‘quvchini tanlang</option>{(students.data||[]).map(s=><option key={s.id} value={s.id}>{s.firstName} {s.lastName} — {s.groupName}</option>)}</select></FormField>{err&&<p className="mb-3 text-sm text-red-600">{err}</p>}<Button type="submit" isLoading={busy} className="w-full">Saqlash</Button></form></Modal></div>}
